DROP TABLE IF EXISTS AccountSettings CASCADE;
DROP TABLE IF EXISTS AccountFollow CASCADE;

DROP TABLE IF EXISTS AccountBlab CASCADE;
DROP TABLE IF EXISTS Blab CASCADE;

DROP TABLE IF EXISTS AccountThumb CASCADE;
DROP TABLE IF EXISTS Thumb CASCADE;

DROP TABLE IF EXISTS AccountReblab CASCADE;
DROP TABLE IF EXISTS Reblab CASCADE;

DROP TABLE IF EXISTS Account CASCADE;