DROP TABLE IF EXISTS UserSettings CASCADE;
DROP TABLE IF EXISTS UserFollow CASCADE;

DROP TABLE IF EXISTS UserBlab CASCADE;
DROP TABLE IF EXISTS Blab CASCADE;

DROP TABLE IF EXISTS UserThumb CASCADE;
DROP TABLE IF EXISTS Thumb CASCADE;

DROP TABLE IF EXISTS UserReblab CASCADE;
DROP TABLE IF EXISTS Reblab CASCADE;

DROP TABLE IF EXISTS User CASCADE;